import {Quicksand} from "next/font/google"
import "./globals.css";
import { Navigation } from "@/components/Navigation";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "Tasks App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({subsets:['latin']});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} antialiased`}
      >
        <div className="container mx-auto p-6">
        <Navigation/>
        {children}
        <Toaster/>
        </div>
      </body>
    </html>
  );
}
